language: node_js
sudo: false
node_js:
- '6'
before_install:
- npm install -g npm; npm --version
before_script:
- node tasks/build.js
script:
- node tasks/sauce-tests.js
addons:
  sauce_connect: true
