language: node_js
sudo: false
node_js:
- '8'
before_script:
- webpack
script:
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run ci:fast; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run ci; fi'
addons:
  sauce_connect: true
