language: node_js
sudo: false
node_js:
- '6'
before_script:
- npm install -g gulp
- gulp build
script: 
- gulp sauce-tests
env:
  global:
  - secure: Byd48iC3+NlETw6sDeGmIosSjFMiOTentw+DbKxmgiYg0d3mrg5aq3HaZZtPT1MgH7auFrLXtVaiK1lDaDmRq+p2WlKOWK4WgN0/UxyzRL5b/dYNU4chijEZrYTa45CGXTwLaPf2Wbq2ncbzbOgBEZxiFHKvI0dwg57U7sDa/lMcTHNOcnLXcVHu5K11cs6N3WcqyLNZiHJd9YhokDFI2aCmdSizfTElPofIWKoxt4i5kCYGpzSNTWr2TsHJc6Ls4Y4Abve4rg6GAYpKeeiuTxXOwbJ5dI8u0aRDd+eCGbtmbMSrOHYZXQCw5xceLrjonovXPDZm4UtHHZRKHE1+e23La+GsH2MIVUApl4Zc1R6lJ1omTjSQt8KHcFV2P0MxSxnOOGA7NPLATTa++Vu1sXsB8X+AVWoR5alJqfyXMrErOeWgxYNI65tPhoX0sOBalxcn5CLAv3JmkkQBZe5VUS89zkUUxxKu4M5lbc2JEoYbkUFH3xvA+rhrXh8Fh5DKEyd9myb+A6B4Esez1bc4nlV6FuUA95vQ/eauv2F3PC1nhz15kSKKgHrZziONUSopwhtaqo953ifLUEwKShEbhLymnkHvlICYRCI2iEVLhc/aT7sNNa5mk5tP6KUabuVSroyNZWHvmluXfDCxG1X443+Fpt6Czj8stOLOMGDzEVE=
  - secure: cbxLnrhb9vxzioImPnvJlLo0DeQpDGn194ZZfVxBMDi88CkZCSVUkcJCt9Rw+OFfuPGoySSwi2RW9JTCjbk0R0g/NDXvRs8kmMnKbIvjeYmpHsN7n5H3BmRY35FfvTyol87o4lBuKTHxLZrYs3zKgthpXnQ4crhGILymmsgaDqpDpmPp5I6gkZ2qHgP1cOWThZra3SYMhP6vArqguikxa4fA6HVSbX8nURohK4eIT6WoPGhZgexSIRIVS8t8scmYkwMV8XOrrdhT23sbtLmj56CsA2RIbF9yUXo2uJtlNjzPnMiAK5A98Rg4zWRaGbp8z8RUpUYIO8RyU9nZ2iWRD2mNTTkn8vEX3JgIVlUhngdrBuYuUN/25B+2HAbfrTuY5jK5pXUxgFX+USj1eOjgjtGiO/w5uCzDsI/GVeK6flbwZ1DkhImkhaTCF2Qwa1XlnE3MqkDtMKHeo1tRhehqttNklbjWWBLW5ad1dl4+urNM9PN7LFEhyoIHHUpRKV6AUvc0crBaWULOJqzSFpNSfFpMBo9ip6xO+d36EAG+4yh7i4BmY/ZmIRySeY7HXWWm3AJXHEBMGnXJ8P0ws+fWZGurQGVFKOuiNWZelEFKXYbDONV0jQGYI4360ylDHp7uV/I0VcolGF45WUqit9ea8EzgQDfYuURMY/hwlGxMLk4=
