language: node_js
sudo: false
node_js:
- '6'
before_script:
- npm install -g gulp
- gulp build
script:
- gulp sauce-tests
addons:
  sauce_connect:
    username: elix
  jwt:
    secure: XO/30X1I805SIS/jxgNryaC4zaLhI1X/6xaZvwp2RjqeggYdvfRSAfZI5xdfzHa68skmo4T4++zCRN1vwe11xZo7UvRgrCGmAqs8nbWDzViV6OR8+j2dVXcX7rWAgOwN7NfX0kI2LiSgn7z3/t+poocEkMV0qQIDOnrXTQtEFiau5luPTATcoxkDd8BbZF59xehUSCJIu9j3BtSFLcfCtWH8pPyoMkIcdsW6wSf3t01lrioyU3tAJfv9PEcjyj6zj5f729ZTmL45CXAgToK29YjUYQNxftyLoatn1b/7Wg7sTQmvpAJD9TMhij3gTef8y9xWUPwH+yrvJN5kNhngl6luwvRaM7Nt8/6i+pQmTGTrA/odY19pDCsofsWdMXRasAZoNizVdeBu0RCnBl6o73wydq6AsDcBqhijwwPuqiyNKURZ0ucc3kF7d7r7s9xbicfHaVuL6XnqKoDSqNZtKQqX3EwItk+HWl7tVL7FmJGXoahjA5iRJ36HRUR9OxD92GVjIZj/1Y3VhMM1yDP6poi1JqnKC9NwG7TL878082YZaUcyocan9CCAWCziJAwWcIMlZerlWacU/N9DMyVIzHIB1OSAq0oj4GzfpcLMd8Eeri2fqMqs4JnPZ2g4DBJYQoWurLath6BFSGFn0NdUqgN0FdYAi62xNVM64V3Uxe0=
