/*
 * The complete set of Elix elements and mixins.
 *
 * This file is the primary entry point to the Elix package, so its exports are
 * what is obtained if you write `import * from "elix"`. However, in
 * production use it will be much more efficient to directly load just the
 * components you need from the /src folder. This file is also used during
 * testing, as it causes all Elix's elements to be loaded.
 *
 * NOTE: Do not edit this file by hand. This file is generated during
 * publishing, or you can regenerate it with `npm run prepublishOnly`.
 */

// Files that export a single object.
export { default as AlertDialog } from "./base/AlertDialog.js";
export { default as AriaListMixin } from "./base/AriaListMixin.js";
export { default as AriaMenuMixin } from "./base/AriaMenuMixin.js";
export { default as AriaRoleMixin } from "./base/AriaRoleMixin.js";
export { default as ArrowDirectionButton } from "./plain/ArrowDirectionButton.js";
export { default as ArrowDirectionMixin } from "./base/ArrowDirectionMixin.js";
export { default as AttributeMarshallingMixin } from "./core/AttributeMarshallingMixin.js";
export { default as AutoCompleteComboBox } from "./base/AutoCompleteComboBox.js";
export { default as AutoCompleteInput } from "./base/AutoCompleteInput.js";
export { default as AutoSizeTextarea } from "./base/AutoSizeTextarea.js";
export { default as Backdrop } from "./base/Backdrop.js";
export { default as Button } from "./plain/Button.js";
export { default as CalendarDay } from "./base/CalendarDay.js";
export { default as CalendarDayButton } from "./base/CalendarDayButton.js";
export { default as CalendarDayNamesHeader } from "./base/CalendarDayNamesHeader.js";
export { default as CalendarDays } from "./base/CalendarDays.js";
export { default as CalendarElementMixin } from "./base/CalendarElementMixin.js";
export { default as CalendarMonth } from "./base/CalendarMonth.js";
export { default as CalendarMonthNavigator } from "./base/CalendarMonthNavigator.js";
export { default as CalendarMonthYearHeader } from "./base/CalendarMonthYearHeader.js";
export { default as Carousel } from "./base/Carousel.js";
export { default as CarouselSlideshow } from "./base/CarouselSlideshow.js";
export { default as CarouselWithThumbnails } from "./base/CarouselWithThumbnails.js";
export { default as CenteredStrip } from "./base/CenteredStrip.js";
export { default as CenteredStripHighlight } from "./plain/CenteredStripHighlight.js";
export { default as CenteredStripOpacity } from "./base/CenteredStripOpacity.js";
export { default as ComboBox } from "./base/ComboBox.js";
export { default as ComposedFocusMixin } from "./base/ComposedFocusMixin.js";
export { default as ContentItemsMixin } from "./base/ContentItemsMixin.js";
export { default as CrossfadeStage } from "./base/CrossfadeStage.js";
export { default as DarkModeMixin } from "./base/DarkModeMixin.js";
export { default as DateComboBox } from "./base/DateComboBox.js";
export { default as DateInput } from "./base/DateInput.js";
export { default as DelegateFocusMixin } from "./base/DelegateFocusMixin.js";
export { default as DelegateItemsMixin } from "./base/DelegateItemsMixin.js";
export { default as Dialog } from "./base/Dialog.js";
export { default as DialogModalityMixin } from "./base/DialogModalityMixin.js";
export { default as DirectionSelectionMixin } from "./base/DirectionSelectionMixin.js";
export { default as DisabledMixin } from "./base/DisabledMixin.js";
export { default as Drawer } from "./base/Drawer.js";
export { default as DrawerWithGrip } from "./base/DrawerWithGrip.js";
export { default as DropdownList } from "./base/DropdownList.js";
export { default as EffectMixin } from "./base/EffectMixin.js";
export { default as ExpandablePanel } from "./base/ExpandablePanel.js";
export { default as ExpandableSection } from "./base/ExpandableSection.js";
export { default as Explorer } from "./base/Explorer.js";
export { default as FilterComboBox } from "./base/FilterComboBox.js";
export { default as FilterListBox } from "./base/FilterListBox.js";
export { default as FocusCaptureMixin } from "./base/FocusCaptureMixin.js";
export { default as FocusVisibleMixin } from "./base/FocusVisibleMixin.js";
export { default as FormElementMixin } from "./base/FormElementMixin.js";
export { default as GenericMixin } from "./base/GenericMixin.js";
export { default as HamburgerMenuButton } from "./base/HamburgerMenuButton.js";
export { default as Hidden } from "./base/Hidden.js";
export { default as HoverMixin } from "./base/HoverMixin.js";
export { default as Input } from "./base/Input.js";
export { default as ItemsTextMixin } from "./base/ItemsTextMixin.js";
export { default as KeyboardDirectionMixin } from "./base/KeyboardDirectionMixin.js";
export { default as KeyboardMixin } from "./base/KeyboardMixin.js";
export { default as KeyboardPagedSelectionMixin } from "./base/KeyboardPagedSelectionMixin.js";
export { default as KeyboardPrefixSelectionMixin } from "./base/KeyboardPrefixSelectionMixin.js";
export { default as LanguageDirectionMixin } from "./base/LanguageDirectionMixin.js";
export { default as ListBox } from "./base/ListBox.js";
export { default as ListComboBox } from "./base/ListComboBox.js";
export { default as ListExplorer } from "./base/ListExplorer.js";
export { default as ListWithSearch } from "./base/ListWithSearch.js";
export { default as Menu } from "./base/Menu.js";
export { default as PlainMenuButton } from "./plain/MenuButton.js";
export { default as MenuItem } from "./base/MenuItem.js";
export { default as MenuSeparator } from "./base/MenuSeparator.js";
export { default as ModalBackdrop } from "./base/ModalBackdrop.js";
export { default as Modes } from "./base/Modes.js";
export { default as OpenCloseMixin } from "./base/OpenCloseMixin.js";
export { default as Overlay } from "./base/Overlay.js";
export { default as OverlayFrame } from "./base/OverlayFrame.js";
export { default as OverlayMixin } from "./base/OverlayMixin.js";
export { default as PageDot } from "./base/PageDot.js";
export { default as PageNumbersMixin } from "./base/PageNumbersMixin.js";
export { default as PlayControlsMixin } from "./base/PlayControlsMixin.js";
export { default as Popup } from "./base/Popup.js";
export { default as PlainPopupButton } from "./plain/PopupButton.js";
export { default as PopupModalityMixin } from "./base/PopupModalityMixin.js";
export { default as PopupSource } from "./base/PopupSource.js";
export { default as ProgressSpinner } from "./base/ProgressSpinner.js";
export { default as PullToRefresh } from "./base/PullToRefresh.js";
export { default as ReactiveElement } from "./core/ReactiveElement.js";
export { default as ReactiveMixin } from "./core/ReactiveMixin.js";
export { default as ResizeMixin } from "./base/ResizeMixin.js";
export { default as SelectableButton } from "./base/SelectableButton.js";
export { default as SelectedItemTextValueMixin } from "./base/SelectedItemTextValueMixin.js";
export { default as SelectionInViewMixin } from "./base/SelectionInViewMixin.js";
export { default as ShadowTemplateMixin } from "./core/ShadowTemplateMixin.js";
export { default as SingleSelectionMixin } from "./base/SingleSelectionMixin.js";
export { default as Slideshow } from "./base/Slideshow.js";
export { default as SlideshowWithPlayControls } from "./base/SlideshowWithPlayControls.js";
export { default as SlidingPages } from "./base/SlidingPages.js";
export { default as SlidingStage } from "./base/SlidingStage.js";
export { default as SlotContentMixin } from "./base/SlotContentMixin.js";
export { default as SlotItemsMixin } from "./base/SlotItemsMixin.js";
export { default as SwipeCommandsMixin } from "./base/SwipeCommandsMixin.js";
export { default as SwipeDirectionMixin } from "./base/SwipeDirectionMixin.js";
export { default as TabButton } from "./base/TabButton.js";
export { default as TabStrip } from "./base/TabStrip.js";
export { default as Tabs } from "./base/Tabs.js";
export { default as TapSelectionMixin } from "./base/TapSelectionMixin.js";
export { default as Thumbnail } from "./base/Thumbnail.js";
export { default as TimerSelectionMixin } from "./base/TimerSelectionMixin.js";
export { default as Toast } from "./base/Toast.js";
export { default as TouchSwipeMixin } from "./base/TouchSwipeMixin.js";
export { default as TrackpadSwipeMixin } from "./base/TrackpadSwipeMixin.js";
export { default as TransitionEffectMixin } from "./base/TransitionEffectMixin.js";
export { default as WrappedStandardElement } from "./base/WrappedStandardElement.js";

// Files that export multiple objects.
// As of Sept 2019, there's no way to simultaneously import a collection of
// objects and then export them as a named object, so we have to do the import
// and export in separate steps.
import * as accessibilityImport from "./base/accessibility.js";
// @ts-ignore
export const accessibility = accessibilityImport;

import * as calendarImport from "./base/calendar.js";
// @ts-ignore
export const calendar = calendarImport;

import * as constantsImport from "./base/constants.js";
// @ts-ignore
export const constants = constantsImport;

import * as contentImport from "./base/content.js";
// @ts-ignore
export const content = contentImport;

import * as fractionalSelectionImport from "./base/fractionalSelection.js";
// @ts-ignore
export const fractionalSelection = fractionalSelectionImport;

import * as internalImport from "./base/internal.js";
// @ts-ignore
export const internal = internalImport;

import * as scrollingImport from "./base/scrolling.js";
// @ts-ignore
export const scrolling = scrollingImport;

import * as templateImport from "./core/template.js";
// @ts-ignore
export const template = templateImport;

import * as utilitiesImport from "./core/utilities.js";
// @ts-ignore
export const utilities = utilitiesImport;
